site_name: Optimus Artifact Expressions (Artifact Type and Test Type Combinations)
nav:
   - "Home": index.md
   - "cisco_asa.acl_object": ArtifactTypes/ciscoASA/cisco_asa_acl_object.md
   - "cisco_asa.line_object": ArtifactTypes/ciscoASA/cisco_asa.line_object.md
   - "cisco_asa.line_object_intf_physical_name": ArtifactTypes/ciscoASA/cisco_asa.line_object_intf_physical_name.md
   - "cisco_asa.line_object_with_untrusted_interfaces": ArtifactTypes/ciscoASA/cisco_asa.line_object_with_untrusted_interfaces.md
   - "cisco_asa.password_policy": ArtifactTypes/ciscoASA/cisco_asa.password_policy.md 
   - "cisco_asa.snmp_group_object": ArtifactTypes/ciscoASA/cisco_asa.snmp_group_object.md
   - "cisco_asa.snmp_host_object": ArtifactTypes/ciscoASA/cisco_asa.snmp_host_object.md
   - "cisco_asa.snmp_user_object": ArtifactTypes/ciscoASA/cisco_asa.snmp_user_object.md
   - "cisco_asa.version_object": ArtifactTypes/ciscoASA/cisco_asa.version_object.md
   - "cisco_ios.bgp_neighbor_config": ArtifactTypes/ciscoIOS/cisco_ios.bgp_neighbor_config.md
   - "cisco_ios.global": ArtifactTypes/ciscoIOS/cisco_ios.global.md
   - "cisco_ios.interface": ArtifactTypes/ciscoIOS/cisco_ios.interface.md
   - "cisco_ios.line": ArtifactTypes/ciscoIOS/cisco_ios.line.md
   - "cisco_ios.line_v2": ArtifactTypes/ciscoIOS/cisco_ios.line_v2.md
   - "cisco_ios.routing_protocol_auth_intf": ArtifactTypes/ciscoIOS/cisco_ios.routing_protocol_auth_intf.md
   - "cisco_ios.section": ArtifactTypes/ciscoIOS/cisco_ios.section.md
   - "cisco_ios.section_custom_router_ospf": ArtifactTypes/ciscoIOS/cisco_ios.section_custom_router_ospf.md
   - "cisco_ios.snmp": ArtifactTypes/ciscoIOS/cisco_ios.snmp.md
   - "cisco_ios.snmp_community": ArtifactTypes/ciscoIOS/cisco_ios.snmp_community.md
   - "cisco_ios.snmp_group": ArtifactTypes/ciscoIOS/cisco_ios.snmp_group.md
   - "cisco_ios.snmp_host": ArtifactTypes/ciscoIOS/cisco_ios.snmp_host.md
   - "cisco_ios.snmp_user": ArtifactTypes/ciscoIOS/cisco_ios.snmp_user.md 
   - "iis.applicationhostconfig": ArtifactTypes/iis/iis.applicationhostconfig.md
   - "iis.applicationpool": ArtifactTypes/iis/iis.applicationpool.md
   - "iis.site.binding": ArtifactTypes/iis/iis.site.binding.md
   - "iis.site.systemweb": ArtifactTypes/iis/iis.site.systemweb.md
   - "iis.webserverconfig": ArtifactTypes/iis/iis.webserverconfig.md
   - "independent.environmentvariable58_v1": ArtifactTypes/independent/independent.environmentvariable58_v1.md
   - "independent.sql57_sqlserver_query_each_database_v1": ArtifactTypes/independent/independent.sql57_sqlserver_query_each_database_v1.md
   - "independent.sql57_v1": ArtifactTypes/independent/independent.sql57_v1.md
   - "independent.text_file_content_tomcat_v1": ArtifactTypes/independent/independent.text_file_content_tomcat_v1.md
   - "independent.text_file_content_v1": ArtifactTypes/independent/independent.text_file_content_v1.md
   - "independent.unknown": ArtifactTypes/independent/independent.unknown.md
   - "independent.xmlfilecontent_tomcat_v1": ArtifactTypes/independent/independent.xmlfilecontent_tomcat_v1.md
   - "ms-sql.multi-db-query_sce_v1": ArtifactTypes/independent/ms-sql.multi-db-query_sce_v1.md
   - "oracledb_tenant.sql57_v1": ArtifactTypes/independent/oracledb_tenant.sql57_v1.md
   - "kubernetes.kubepsp_v1": ArtifactTypes/kubernetes/kubernetes.kubepsp_v1.md 
   - "macos.gatekeeper_v1": ArtifactTypes/macos/macos.gatekeeper_v1.md
   - "macos.keychain_v1": ArtifactTypes/macos/macos.keychain_v1.md
   - "macos.plist511_v1": ArtifactTypes/macos/macos.plist511_v1.md
   - "macos.systemprofiler_v1": ArtifactTypes/macos/macos.systemprofiler_v1.md
   - "macos.systemsetup_v1": ArtifactTypes/macos/macos.systemsetup_v1.md
   - "linux.auditd_rule_v1": ArtifactTypes/unixlinux/linux.auditd_rule_v1.md
   - "linux.auditd_rule_v2": ArtifactTypes/unixlinux/linux.auditd_rule_v2.md
   - "linux.custom_object_v1": ArtifactTypes/unixlinux/linux.custom_object_v1.md 
   - "linux.debian_package_v1": ArtifactTypes/unixlinux/linux.debian_package_v1.md
   - "linux.kernel_module_v1": ArtifactTypes/unixlinux/linux.kernel_module_v1.md
   - "linux.partition_device_v1": ArtifactTypes/unixlinux/linux.partition_device_v1.md
   - "linux.partition_options_v1": ArtifactTypes/unixlinux/linux.partition_options_v1.md
   - "linux.partition_v1": ArtifactTypes/unixlinux/linux.partition_v1.md
   - "linux.rpm_package_v1": ArtifactTypes/unixlinux/linux.rpm_package_v1.md
   - "linux.service_v1": ArtifactTypes/unixlinux/linux.service_v1.md
   - "linux.software_package_v1": ArtifactTypes/unixlinux/linux.software_package_v1.md
   - "linux.systemd_unit_dependency_v1": ArtifactTypes/unixlinux/linux.systemd_unit_dependency_v1.md
   - "linux.systemd_unit_property_v1": ArtifactTypes/unixlinux/linux.systemd_unit_property_v1.md
   - "linux.upstart_service_v1": ArtifactTypes/unixlinux/linux.upstart_service_v1.md
   - "sce_check_v1": ArtifactTypes/unixlinux/sce_check_v1.md
   - "unix.chkconfig_service_v2": ArtifactTypes/unixlinux/unix.chkconfig_service_v2.md
   - "unix.chkconfig_service_v1": ArtifactTypes/unixlinux/unix.chkconfig_service_v1.md
   - "unix.command_output_v1": ArtifactTypes/unixlinux/unix.command_output_v1.md
   - "unix.file_collection_v1": ArtifactTypes/unixlinux/unix.file_collection_v1.md
   - "unix.file_collection_v2": ArtifactTypes/unixlinux/unix.file_collection_v2.md
   - "unix.individual_file_tomcat_v1": ArtifactTypes/unixlinux/unix.individual_file_tomcat_v1.md
   - "unix.individual_file_v1": ArtifactTypes/unixlinux/unix.individual_file_v1.md
   - "unix.inetd_service_v1": ArtifactTypes/unixlinux/unix.inetd_service_v1.md
   - "unix.kernel_parameter_v1": ArtifactTypes/unixlinux/unix.kernel_parameter_v1.md
   - "unix.proc_info_v1": ArtifactTypes/unixlinux/unix.proc_info_v1.md
   - "unix.process58_v2": ArtifactTypes/unixlinux/unix.process58_v2.md
   - "unix.shadow_parameter_v1": ArtifactTypes/unixlinux/unix.shadow_parameter_v1.md
   - "unix.sshd_parameter_v1": ArtifactTypes/unixlinux/unix.sshd_parameter_v1.md
   - "unix.sshd_v2": ArtifactTypes/unixlinux/unix.sshd_v2.md
   - "unix.uname_parameter_v1": ArtifactTypes/unixlinux/unix.uname_parameter_v1.md
   - "unix.xinetd_service_v1": ArtifactTypes/unixlinux/unix.xinetd_service_v1.md
   - "windows.auditeventsubcategories": ArtifactTypes/windows/windows.auditeventsubcategories.md
   - "windows.lockoutpolicyobject": ArtifactTypes/windows/windows.lockoutpolicyobject.md
   - "windows.passwordpolicyobject": ArtifactTypes/windows/windows.passwordpolicyobject.md
   - "windows.privilegeassignment": ArtifactTypes/windows/windows.privilegeassignment.md
   - "windows.registry.value": ArtifactTypes/windows/windows.registry.value.md
   - "windows.registry_value_v2": ArtifactTypes/windows/windows.registry_value_v2.md
   - "windows.rsop.security_setting_boolean": ArtifactTypes/windows/windows.rsop.security_setting_boolean.md
   - "windows.sid_sid_v1": ArtifactTypes/windows/windows.sid_sid_v1.md
   - "windows.user": ArtifactTypes/windows/windows.user.md
   - "windows.user_registry_value_v1": ArtifactTypes/windows/windows.user_registry_value_v1.md
   - "windows.user_sid55": ArtifactTypes/windows/windows.user_sid55.md
   - "windows.userright_v2": ArtifactTypes/windows/windows.userright_v2.md
   - "windows.userrightsassignment": ArtifactTypes/windows/windows.userrightsassignment.md
   - "windows.userrightsassignmentdeny": ArtifactTypes/windows/windows.userrightsassignmentdeny.md
   - "vmware.vds_portgroup_v2": ArtifactTypes/vmware/vmware.vds_portgroup_v2.md
   - "vmware.vds_v2": ArtifactTypes/vmware/vmware.vds_v2.md
   - "vmware.vhmost.lockdown_mode": ArtifactTypes/vmware/vmware.vmhost.lockdown_mode.md
   - "vmware.virtual_machine.advanced_setting": ArtifactTypes/vmware/vmware.virtual_machine.advanced_setting.md
   - "vmware.virtual_machine.device.harddisk": ArtifactTypes/vmware/vmware.virtual_machine.device.harddisk.md
   - "vmware.virtual_machine.device_state": ArtifactTypes/vmware/vmware.virtual_machine.device_state.md
   - "vmware.virtual_port_group": ArtifactTypes/vmware/vmware.virtual_port_group.md
   - "vmware.virtual_portgroup_v2": ArtifactTypes/vmware/vmware.virtual_portgroup_v2.md
   - "vmware.vm_advancedsetting_v2": ArtifactTypes/vmware/vmware.vm_advancedsetting_v2.md
   - "vmware.vm_device_v2": ArtifactTypes/vmware/vmware.vm_device_v2.md
   - "vmware.vm_harddiskdevice_v2": ArtifactTypes/vmware/vmware.vm_harddiskdevice_v2.md
   - "vmware.vmhost.acceptance_level": ArtifactTypes/vmware/vmware.vmhost.acceptance_level.md
   - "vmware.vmhost.account": ArtifactTypes/vmware/vmware.vmhost.account.md
   - "vmware.vmhost.advanced_setting": ArtifactTypes/vmware/vmhost.vmhost.advanced_setting.md
   - "vmware.vmhost.authentication_setting": ArtifactTypes/vmware/vmhost.vmhost.authentication_setting.md
   - "vmware.vmhost.bus_adapter.iscsi.chap.mutual": ArtifactTypes/vmware/vmware.vmhost.bus_adapter.iscsi.chap.mutual.md
   - "vmware.vmhost.core_dump.network_server": ArtifactTypes/vmware/vmware.vmhost.core_dump.network_server.md
   - "vmware.vmhost.firewall_exception.all_ip": ArtifactTypes/vmware/vmware.vmhost.firewall_exception.all_ip.md
   - "vmware.vmhost.module.signature_status": ArtifactTypes/vmware/vmware.vmhost.module.signature_status.md
   - "vmware.vmhost.ntp_server": ArtifactTypes/vmware/vmware.vmhost.ntp_server.md
   - "vmware.vmhost.service.state": ArtifactTypes/vmware/vmware.vmhost.service.state.md
   - "vmware.vmhost.vib": ArtifactTypes/vmware/vmware.vmhost.vib.md
   - "vmware.vmhost.virtual_switch": ArtifactTypes/vmware/vmware.vmhost.virtual_switch.md
   - "vmware.vmhost.webserverssl": ArtifactTypes/vmware/vmware.vmhost.webserverssl.md
   - "vmware.vmhost_acceptancelevel_v2": ArtifactTypes/vmware/vmware.vmhost_acceptancelevel_v2.md
   - "vmware.vmhost_account_v2": ArtifactTypes/vmware/vmware.vmhost_account_v2.md
   - "vmware.vmhost_advancedsetting_v2": ArtifactTypes/vmware/vmware.vmhost_advancedsetting_v2.md
   - "vmware.vmhost_authentication_v2": ArtifactTypes/vmware/vmware.vmhost_authentication_v2.md
   - "vmware.vmhost_busadapter_v2": ArtifactTypes/vmware/vmware.vmhost_busadapter_v2.md
   - "vmware.vmhost_coredump_v2": ArtifactTypes/vmware/vmware.vmhost_coredump_v2.md
   - "vmware.vmhost_firewallexception_v2": ArtifactTypes/vmware/vmware.vmhost_firewallexception_v2
   - "vmware.vmhost_lockdown_v2": ArtifactTypes/vmware/vmware.vmhost_lockdown_v2.md
   - "vmware.vmhost_module_v2": ArtifactTypes/vmware/vmware.vmhost_module_v2.md
   - "vmware.vmhost_ntpserver_v2": ArtifactTypes/vmware/vmware.vmhost_ntpserver_v2.md
   - "vmware.vmhost_service_v2": ArtifactTypes/vmware/vmware.vmhost_service_v2.md
   - "vmware.vmhost_vib_v2": ArtifactTypes/vmware/vmware.vmhost_vib_v2.md
   - "vmware.vmhost_vswitchpolicy_v2": ArtifactTypes/vmware/vmware.vmhost_vswitchpolicy_v2.md
   - "vmware.vmhost_webserverssl_v2": ArtifactTypes/vmware/vmware.vmhost_webserverssl_v2.md
   - "License Information": License Information.md
   - "Change Log": Change Log.md
theme:
  name: readthedocs