site_name: Optimus Artifact Expressions (Artifact Type and Test Type Combinations)
nav:
   - "Home": index.md
   - "ciscoASA/cisco_asa.acl_object": cisco_asa_acl_object.md
   - "ciscoASA/cisco_asa.line_object": cisco_asa.line_object.md
   - "ciscoASA/cisco_asa.line_object_intf_physical_name": cisco_asa.line_object_intf_physical_name.md
   - "ciscoASA/cisco_asa.line_object_with_untrusted_interfaces": cisco_asa.line_object_with_untrusted_interfaces.md
   - "ciscoASA/cisco_asa.password_policy": cisco_asa.password_policy.md 
   - "ciscoASA/cisco_asa.snmp_group_object": cisco_asa.snmp_group_object.md
   - "ciscoASA/cisco_asa.snmp_host_object": cisco_asa.snmp_host_object.md
   - "ciscoASA/cisco_asa.snmp_user_object": cisco_asa.snmp_user_object.md
   - "ciscoASA/cisco_asa.version_object": cisco_asa.version_object.md
   - "ciscoIOS/cisco_ios.bgp_neighbor_config": cisco_ios.bgp_neighbor_config.md
   - "ciscoIOS/cisco_ios.global": cisco_ios.global.md
   - "ciscoIOS/cisco_ios.interface": cisco_ios.interface.md
   - "ciscoIOS/cisco_ios.line": cisco_ios.line.md
   - "ciscoIOS/cisco_ios.line_v2": cisco_ios.line_v2.md
   - "ciscoIOS/cisco_ios.routing_protocol_auth_intf": cisco_ios.routing_protocol_auth_intf.md
   - "ciscoIOS/cisco_ios.section": cisco_ios.section.md
   - "ciscoIOS/cisco_ios.section_custom_router_ospf": cisco_ios.section_custom_router_ospf.md
   - "ciscoIOS/cisco_ios.snmp": cisco_ios.snmp.md
   - "ciscoIOS/cisco_ios.snmp_community": cisco_ios.snmp_community.md
   - "ciscoIOS/cisco_ios.snmp_group": cisco_ios.snmp_group.md
   - "ciscoIOS/cisco_ios.snmp_host": cisco_ios.snmp_host.md
   - "ciscoIOS/cisco_ios.snmp_user": cisco_ios.snmp_user.md 
   - "iis/iis.applicationhostconfig": iis.applicationhostconfig.md
   - "iis/iis.applicationpool": iis.applicationpool.md
   - "iis/iis.site.binding": iis.site.binding.md
   - "iis/iis.site.systemweb": iis.site.systemweb.md
   - "iis/iis.webserverconfig": iis.webserverconfig.md
   - "independent/independent.environmentvariable58_v1": independent.environmentvariable58_v1.md
   - "independent/independent.sql57_sqlserver_query_each_database_v1": independent.sql57_sqlserver_query_each_database_v1.md
   - "independent/independent.sql57_v1": independent.sql57_v1.md
   - "independent/independent.text_file_content_tomcat_v1": independent.text_file_content_tomcat_v1.md
   - "independent/independent.text_file_content_v1": independent.text_file_content_v1.md
   - "independent/independent.unknown": independent.unknown.md
   - "independent/independent.xmlfilecontent_tomcat_v1": independent.xmlfilecontent_tomcat_v1.md
   - "independent/ms-sql.multi-db-query_sce_v1": ms-sql.multi-db-query_sce_v1.md
   - "independent/oracledb_tenant.sql57_v1": oracledb_tenant.sql57_v1.md
   - "kubernetes/kubernetes.kubepsp_v1": kubernetes.kubepsp_v1.md 
   - "macos/macos.gatekeeper_v1": macos.gatekeeper_v1.md
   - "macos/macos.keychain_v1": macos.keychain_v1.md
   - "macos/macos.plist511_v1": macos.plist511_v1.md
   - "macos/macos.systemprofiler_v1": macos.systemprofiler_v1.md
   - "macos/macos.systemsetup_v1": macos.systemsetup_v1.md
   - "unixlinux/linux.auditd_rule_v1": linux.auditd_rule_v1.md
   - "unixlinux/linux.auditd_rule_v2": linux.auditd_rule_v2.md
   - "unixlinux/linux.custom_object_v1": linux.custom_object_v1.md 
   - "unixlinux/linux.debian_package_v1": linux.debian_package_v1.md
   - "unixlinux/linux.kernel_module_v1": linux.kernel_module_v1.md
   - "unixlinux/linux.partition_device_v1": linux.partition_device_v1.md
   - "unixlinux/linux.partition_options_v1": linux.partition_options_v1.md
   - "unixlinux/linux.partition_v1": linux.partition_v1.md
   - "unixlinux/linux.rpm_package_v1": linux.rpm_package_v1.md
   - "unixlinux/linux.service_v1": linux.service_v1.md
   - "unixlinux/linux.software_package_v1": linux.software_package_v1.md
   - "unixlinux/linux.systemd_unit_dependency_v1": linux.systemd_unit_dependency_v1.md
   - "unixlinux/linux.systemd_unit_property_v1": linux.systemd_unit_property_v1.md
   - "unixlinux/linux.upstart_service_v1": linux.upstart_service_v1.md
   - "unixlinux/sce_check_v1": sce_check_v1.md
   - "unixlinux/unix.chkconfig_service_v2": unix.chkconfig_service_v2.md
   - "unixlinux/unix.chkconfig_service_v1": unix.chkconfig_service_v1.md
   - "unixlinux/unix.command_output_v1": unix.command_output_v1.md
   - "unixlinux/unix.file_collection_v1": unix.file_collection_v1.md
   - "unixlinux/unix.file_collection_v2": unix.file_collection_v2.md
   - "unixlinux/unix.individual_file_tomcat_v1": unix.individual_file_tomcat_v1.md
   - "unixlinux/unix.individual_file_v1": unix.individual_file_v1.md
   - "unixlinux/unix.inetd_service_v1": unix.inetd_service_v1.md
   - "unixlinux/unix.kernel_parameter_v1": unix.kernel_parameter_v1.md
   - "unixlinux/unix.proc_info_v1": unix.proc_info_v1.md
   - "unixlinux/unix.process58_v2": unix.process58_v2.md
   - "unixlinux/unix.shadow_parameter_v1": unix.shadow_parameter_v1.md
   - "unixlinux/unix.sshd_parameter_v1": unix.sshd_parameter_v1.md
   - "unixlinux/unix.sshd_v2": unix.sshd_v2.md
   - "unixlinux/unix.uname_parameter_v1": unix.uname_parameter_v1.md
   - "unixlinux/unix.xinetd_service_v1": unix.xinetd_service_v1.md
   - "windows/windows.auditeventsubcategories": windows.auditeventsubcategories.md
   - "windows/windows.lockoutpolicyobject": windows.lockoutpolicyobject.md
   - "windows/windows.passwordpolicyobject": windows.passwordpolicyobject.md
   - "windows/windows.privilegeassignment": windows.privilegeassignment.md
   - "windows/windows.registry.value": windows.registry.value.md
   - "windows/windows.registry_value_v2": windows.registry_value_v2.md
   - "windows/windows.rsop.security_setting_boolean": windows.rsop.security_setting_boolean.md
   - "windows/windows.sid_sid_v1": windows.sid_sid_v1.md
   - "windows/windows.user": windows.user.md
   - "windows/windows.user_registry_value_v1": windows.user_registry_value_v1.md
   - "windows/windows.user_sid55": windows.user_sid55.md
   - "windows/windows.userright_v2": windows.userright_v2.md
   - "windows/windows.userrightsassignment": windows.userrightsassignment.md
   - "windows/windows.userrightsassignmentdeny": windows.userrightsassignmentdeny.md
   - "vmware/vmware.vds_portgroup_v2": vmware.vds_portgroup_v2.md
   - "vmware/vmware.vds_v2": vmware.vds_v2.md
   - "vmware/vmware.vhmost.lockdown_mode": vmware.vmhost.lockdown_mode.md
   - "vmware/vmware.virtual_machine.advanced_setting": vmware.virtual_machine.advanced_setting.md
   - "vmware/vmware.virtual_machine.device.harddisk": vmware.virtual_machine.device.harddisk.md
   - "vmware/vmware.virtual_machine.device_state": vmware.virtual_machine.device_state.md
   - "vmware/vmware.virtual_port_group": vmware.virtual_port_group.md
   - "vmware/vmware.virtual_portgroup_v2": vmware.virtual_portgroup_v2.md
   - "vmware/vmware.vm_advancedsetting_v2": vmware.vm_advancedsetting_v2.md
   - "vmware/vmware.vm_device_v2": vmware.vm_device_v2.md
   - "vmware/vmware.vm_harddiskdevice_v2": vmware.vm_harddiskdevice_v2.md
   - "vmware/vmware.vmhost.acceptance_level": vmware.vmhost.acceptance_level.md
   - "vmware/vmware.vmhost.account": vmware.vmhost.account.md
   - "vmware/vmware.vmhost.advanced_setting": vmhost.vmhost.advanced_setting.md
   - "vmware/vmware.vmhost.authentication_setting": vmhost.vmhost.authentication_setting.md
   - "vmware/vmware.vmhost.bus_adapter.iscsi.chap.mutual": vmware.vmhost.bus_adapter.iscsi.chap.mutual.md
   - "vmware/vmware.vmhost.core_dump.network_server": vmware.vmhost.core_dump.network_server.md
   - "vmware/vmware.vmhost.firewall_exception.all_ip": vmware.vmhost.firewall_exception.all_ip.md
   - "vmware/vmware.vmhost.module.signature_status": vmware.vmhost.module.signature_status.md
   - "vmware/vmware.vmhost.ntp_server": vmware.vmhost.ntp_server.md
   - "vmware/vmware.vmhost.service.state": vmware.vmhost.service.state.md
   - "vmware/vmware.vmhost.vib": vmware.vmhost.vib.md
   - "vmware/vmware.vmhost.virtual_switch": vmware.vmhost.virtual_switch.md
   - "vmware/vmware.vmhost.webserverssl": vmware.vmhost.webserverssl.md
   - "vmware/vmware.vmhost_acceptancelevel_v2": vmware.vmhost_acceptancelevel_v2.md
   - "vmware/vmware.vmhost_account_v2": vmware.vmhost_account_v2.md
   - "vmware/vmware.vmhost_advancedsetting_v2": vmware.vmhost_advancedsetting_v2.md
   - "vmware/vmware.vmhost_authentication_v2": vmware.vmhost_authentication_v2.md
   - "vmware/vmware.vmhost_busadapter_v2": vmware.vmhost_busadapter_v2.md
   - "vmware/vmware.vmhost_coredump_v2": vmware.vmhost_coredump_v2.md
   - "vmware/vmware.vmhost_firewallexception_v2": vmware.vmhost_firewallexception_v2
   - "vmware/vmware.vmhost_lockdown_v2": vmware.vmhost_lockdown_v2.md
   - "vmware/vmware.vmhost_module_v2": vmware.vmhost_module_v2.md
   - "vmware/vmware.vmhost_ntpserver_v2": vmware.vmhost_ntpserver_v2.md
   - "vmware/vmware.vmhost_service_v2": vmware.vmhost_service_v2.md
   - "vmware/vmware.vmhost_vib_v2": vmware.vmhost_vib_v2.md
   - "vmware/vmware.vmhost_vswitchpolicy_v2": vmware.vmhost_vswitchpolicy_v2.md
   - "vmware/vmware.vmhost_webserverssl_v2": vmware.vmhost_webserverssl_v2.md
   - "License Information": License Information.md
   - "Change Log": Change Log.md
theme:
  name: readthedocs